[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "dist/functions"

[build.environment]
  NODE_VERSION = "20"
  CI = "true"
  NPM_FLAGS = "--no-optional"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  directory = "dist/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless"]

[functions.api]
  memory = 1024
  timeout = 10

[dev]
  command = "npm run dev"
  targetPort = 5000
  port = 8888
  publish = "dist/public"
  autoLaunch = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self' *.netlify.app; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.tradingview.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' *.netlify.app *.neon.tech ws: wss:; frame-src 'self' *.tradingview.com; worker-src 'self' blob:;"